
firstname = input("Enter first name")
lastname = input("Enter last name")
Country = input("Your country of Origin")
Profession = input("Enter the nature of your current job")
Email = input("Enter your email address")
Phone = input("Enter your phone number")
City = input("Enter your current city of residence")
Address = input("Enter your Mailing address")
fullname = (firstname + " " + lastname)

print("Name:" + "" + (firstname + " " + lastname))
print("country:" + Country)
print("Profession:" + Profession)
print("Email:" + Email)
print("Phone:" + Phone)
print("City:" + City)
print("Address:" + Address)
print()

